# Generated by Django 3.0.5 on 2021-05-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveSmallIntegerField()),
                ('p_length', models.PositiveSmallIntegerField()),
                ('is_letter', models.BooleanField()),
                ('is_digit', models.BooleanField()),
                ('is_symbol', models.BooleanField()),
                ('p_case', models.CharField(max_length=10)),
                ('is_unique', models.BooleanField()),
                ('no_of_results', models.PositiveSmallIntegerField()),
                ('lower_chars', models.PositiveSmallIntegerField()),
                ('upper_chars', models.PositiveSmallIntegerField()),
                ('special_chars', models.PositiveSmallIntegerField()),
                ('numeric_chars', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
