# Generated by Django 3.0.5 on 2021-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presets',
            name='lower_chars',
        ),
        migrations.RemoveField(
            model_name='presets',
            name='numeric_chars',
        ),
        migrations.RemoveField(
            model_name='presets',
            name='special_chars',
        ),
        migrations.RemoveField(
            model_name='presets',
            name='upper_chars',
        ),
        migrations.AddField(
            model_name='presets',
            name='preset_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
